<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Article_model extends CI_Model
{

    public $table = 'article';
    public $v_table = 'v_article';
    public $v_table_best = 'v_bestseller';
    public $id = 'id';
    public $stock = 'stock';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    //get all de la vue
    function get_all_v()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->v_table)->result();
    }
    
    //get
     public function article_zero(){
         $this->db->where('stock', 0);
        return $this->db->get($this->table)->row();
    }
     
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    // get data by id vue
    function get_by_id_v($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->v_table)->row();
    }
    //les produits epuisses
    function get_finished(){
        $this->db->where('stock =', 0);
        return $this->db->get($this->v_table)->row();
    }
    function get_total_finished(){
        $this->db->where('stock =', 0);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    
    public function get_total_weak(){
         $this->db->where('stock <=', 10);
         $this->db->where('stock >', 0);
         $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    public function get_weak(){
         $this->db->where('stock <=', 10);
         $this->db->where('stock >', 0);
         $this->db->from($this->table);
        return $this->db->get($this->v_table)->row();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('codeArticle', $q);
	$this->db->or_like('designation', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('prix', $q);
	$this->db->or_like('idCategorie', $q);
	$this->db->or_like('idFournisseur', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }
      function total_rows_best($q = NULL) {
      
	$this->db->from($this->v_table_best);
        return $this->db->count_all_results();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('codeArticle', $q);
	$this->db->or_like('designation', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('prix', $q);
	$this->db->or_like('idCategorie', $q);
	$this->db->or_like('idFournisseur', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->v_table)->result();
    }
    function get_limit_best_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('codeArticle', $q);
	$this->db->or_like('designation', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('prix', $q);
	$this->db->or_like('idCategorie', $q);
	$this->db->or_like('idFournisseur', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->v_table_best)->result();
    }
    // get data with limit and search
    function get_limit_weak_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('stock <=', 10);
         $this->db->where('stock >', 0);
      
      $this->db->like('codeArticle', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->v_table)->result();
    }
    // get data with limit and search
    function get_limit_finished_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
       
      $this->db->or_like('codeArticle', $q);
        $this->db->where('stock =', 0);
    $this->db->limit($limit, $start);
        return $this->db->get($this->v_table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Article_model.php */
/* Location: ./application/models/Article_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-19 15:29:33 */
/* http://harviacode.com */