<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Utilisateur_model extends CI_Model
{

    public $table = 'utilisateur';
    public $v_table = 'v_utilisateur';
  
    public $id = 'id';
    public $order = 'DESC';
    public $matricule='matricule';
   

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get all
    function get_all_v()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->v_table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    //get user 
    function get_user($matricule){
        $this->db->where($this->matricule,$matricule);
        return $this->db->get($this->table)->row();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nom', $q);
	$this->db->or_like('matricule', $q);
	$this->db->or_like('prenom', $q);
	$this->db->or_like('dateNaissance', $q);
	$this->db->or_like('tel', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('pwd', $q);
	$this->db->or_like('idType', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }
  

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('matricule', $q);
	$this->db->or_like('nom', $q);
	$this->db->or_like('prenom', $q);
	$this->db->or_like('dateNaissance', $q);
	$this->db->or_like('tel', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('pwd', $q);
	$this->db->or_like('idType', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->v_table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Utilisateur_model.php */
/* Location: ./application/models/Utilisateur_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-19 15:29:34 */
/* http://harviacode.com */